# Generated by Django 5.2.7 on 2026-06-05 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=70, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon token.", max_length=40
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex, e.g. #E84A27.", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="trucks/logos/"),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="trucks/heroes/"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Chicago", max_length=64),
                ),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("instagram", models.CharField(blank=True, max_length=64)),
                ("accepts_catering_inquiries", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                        ],
                        default="DRAFT",
                        max_length=8,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="UNVERIFIED",
                        max_length=10,
                    ),
                ),
                (
                    "cuisine_tags",
                    models.ManyToManyField(
                        blank=True, related_name="tagged_trucks", to="trucks.cuisine"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trucks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_cuisine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_trucks",
                        to="trucks.cuisine",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TruckVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("PERMIT", "Permit / license"),
                            ("SOCIAL", "Social account"),
                            ("LIVE_PHOTO", "Coded live photo"),
                            ("CALL", "Call / video"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "evidence_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="verifications/"
                    ),
                ),
                ("evidence_note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLURRY", "Image too blurry"),
                            ("NAME_MISMATCH", "Name mismatch"),
                            ("EXPIRED", "Document expired"),
                            ("SOCIAL_UNVERIFIED", "Could not verify social"),
                            ("NEED_MORE_INFO", "Need more info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="trucks.truck",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
