# Generated by Django 5.2.7 on 2026-06-06 06:04

import apps.core.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truck",
            name="hero_image",
            field=apps.core.images.ProcessedImageField(
                blank=True, null=True, upload_to="trucks/heroes/"
            ),
        ),
        migrations.AlterField(
            model_name="truck",
            name="logo",
            field=apps.core.images.ProcessedImageField(
                blank=True, null=True, upload_to="trucks/logos/"
            ),
        ),
        migrations.AlterField(
            model_name="truckverification",
            name="evidence_image",
            field=apps.core.images.ProcessedImageField(
                blank=True, null=True, upload_to="verifications/"
            ),
        ),
    ]
