import pytest
from rest_framework.test import APIClient

from apps.accounts.tests.factories import OwnerFactory, UserFactory
from apps.trucks.models import Truck, TruckVerification
from apps.trucks.tests.factories import CuisineFactory, TruckFactory

pytestmark = pytest.mark.django_db

URL = "/api/v1/owner/trucks/"


def _payload(cuisine):
    return {"name": "My Truck", "primary_cuisine": cuisine.id, "status": "ACTIVE"}


def test_anonymous_cannot_create_truck():
    resp = APIClient().post(URL, _payload(CuisineFactory()), format="json")
    assert resp.status_code == 401


def test_customer_cannot_create_truck():
    client = APIClient()
    client.force_authenticate(user=UserFactory())  # CUSTOMER by default
    resp = client.post(URL, _payload(CuisineFactory()), format="json")
    assert resp.status_code == 403


def test_owner_can_create_truck():
    owner = OwnerFactory()
    client = APIClient()
    client.force_authenticate(user=owner)
    resp = client.post(URL, _payload(CuisineFactory()), format="json")
    assert resp.status_code == 201
    truck = Truck.objects.get(name="My Truck")
    assert truck.owner == owner
    assert truck.slug  # autogenerated
    assert truck.verification_status == Truck.VerificationStatus.UNVERIFIED


def test_owner_list_shows_only_own_trucks_including_drafts():
    owner = OwnerFactory()
    own = TruckFactory(owner=owner, status=Truck.Status.DRAFT)
    other = TruckFactory()
    client = APIClient()
    client.force_authenticate(user=owner)
    slugs = {t["slug"] for t in client.get(URL).data["results"]}
    assert own.slug in slugs
    assert other.slug not in slugs


def test_owner_cannot_update_another_owners_truck():
    other = TruckFactory()
    client = APIClient()
    client.force_authenticate(user=OwnerFactory())
    resp = client.patch(f"{URL}{other.slug}/", {"name": "Hijack"}, format="json")
    assert resp.status_code == 404


def test_owner_can_update_own_truck():
    owner = OwnerFactory()
    truck = TruckFactory(owner=owner)
    client = APIClient()
    client.force_authenticate(user=owner)
    resp = client.patch(
        f"{URL}{truck.slug}/", {"description": "Updated"}, format="json"
    )
    assert resp.status_code == 200
    truck.refresh_from_db()
    assert truck.description == "Updated"


def test_owner_cannot_self_verify_via_update():
    owner = OwnerFactory()
    truck = TruckFactory(
        owner=owner, verification_status=Truck.VerificationStatus.UNVERIFIED
    )
    client = APIClient()
    client.force_authenticate(user=owner)
    resp = client.patch(
        f"{URL}{truck.slug}/", {"verification_status": "VERIFIED"}, format="json"
    )
    assert resp.status_code == 200
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.UNVERIFIED


def test_owner_request_verification_creates_pending():
    owner = OwnerFactory()
    truck = TruckFactory(
        owner=owner, verification_status=Truck.VerificationStatus.UNVERIFIED
    )
    client = APIClient()
    client.force_authenticate(user=owner)
    resp = client.post(
        f"{URL}{truck.slug}/request_verification/",
        {"method": "PERMIT", "evidence_note": "permit #1"},
        format="json",
    )
    assert resp.status_code == 201
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.PENDING
    assert TruckVerification.objects.filter(
        truck=truck, status=TruckVerification.Status.PENDING
    ).exists()
