import pytest

from apps.trucks.models import Truck, TruckVerification
from apps.trucks.tests.factories import (
    CuisineFactory,
    TruckFactory,
    TruckVerificationFactory,
)

pytestmark = pytest.mark.django_db


def test_truck_slug_autogenerated():
    truck = TruckFactory(name="Taco Loco", slug="")
    assert truck.slug == "taco-loco"


def test_truck_slug_collision_is_suffixed():
    TruckFactory(name="Taco Loco", slug="")
    second = TruckFactory(name="Taco Loco", slug="")
    assert second.slug == "taco-loco-2"


def test_is_publicly_visible_requires_active_and_verified():
    truck = TruckFactory(
        status=Truck.Status.ACTIVE,
        verification_status=Truck.VerificationStatus.VERIFIED,
    )
    assert truck.is_publicly_visible is True

    truck.status = Truck.Status.PAUSED
    assert truck.is_publicly_visible is False

    pending = TruckFactory(
        status=Truck.Status.ACTIVE,
        verification_status=Truck.VerificationStatus.PENDING,
    )
    assert pending.is_publicly_visible is False


def test_cuisine_tags_m2m():
    truck = TruckFactory()
    korean = CuisineFactory(name="Korean")
    mexican = CuisineFactory(name="Mexican")
    truck.cuisine_tags.add(korean, mexican)
    assert truck.cuisine_tags.count() == 2


def test_verification_approve_marks_truck_verified():
    truck = TruckFactory(verification_status=Truck.VerificationStatus.PENDING)
    verification = TruckVerificationFactory(truck=truck)
    verification.approve()
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.VERIFIED
    assert verification.status == TruckVerification.Status.APPROVED


def test_verification_reject_sets_reason_and_status():
    truck = TruckFactory(verification_status=Truck.VerificationStatus.PENDING)
    verification = TruckVerificationFactory(truck=truck)
    verification.reject(reason=TruckVerification.Reason.BLURRY, notes="resend please")
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.REJECTED
    assert verification.reason == TruckVerification.Reason.BLURRY
    assert verification.status == TruckVerification.Status.REJECTED
