import pytest

from apps.trucks.models import Truck, TruckVerification
from apps.trucks.tests.factories import (
    CuisineFactory,
    TruckFactory,
    TruckVerificationFactory,
)

pytestmark = pytest.mark.django_db


def test_truck_slug_autogenerated():
    truck = TruckFactory(name="Taco Loco", slug="")
    assert truck.slug == "taco-loco"


def test_truck_slug_collision_is_suffixed():
    TruckFactory(name="Taco Loco", slug="")
    second = TruckFactory(name="Taco Loco", slug="")
    assert second.slug == "taco-loco-2"


def test_is_publicly_visible_requires_active_and_verified():
    truck = TruckFactory(
        status=Truck.Status.ACTIVE,
        verification_status=Truck.VerificationStatus.VERIFIED,
    )
    assert truck.is_publicly_visible is True

    truck.status = Truck.Status.PAUSED
    assert truck.is_publicly_visible is False

    pending = TruckFactory(
        status=Truck.Status.ACTIVE,
        verification_status=Truck.VerificationStatus.PENDING,
    )
    assert pending.is_publicly_visible is False


def test_cuisine_tags_m2m():
    truck = TruckFactory()
    korean = CuisineFactory(name="Korean")
    mexican = CuisineFactory(name="Mexican")
    truck.cuisine_tags.add(korean, mexican)
    assert truck.cuisine_tags.count() == 2


def test_verification_approve_marks_truck_verified():
    truck = TruckFactory(verification_status=Truck.VerificationStatus.PENDING)
    verification = TruckVerificationFactory(truck=truck)
    verification.approve()
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.VERIFIED
    assert verification.status == TruckVerification.Status.APPROVED


def test_verification_reject_sets_reason_and_status():
    truck = TruckFactory(verification_status=Truck.VerificationStatus.PENDING)
    verification = TruckVerificationFactory(truck=truck)
    verification.reject(reason=TruckVerification.Reason.BLURRY, notes="resend please")
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.REJECTED
    assert verification.reason == TruckVerification.Reason.BLURRY
    assert verification.status == TruckVerification.Status.REJECTED


# --- Verification submission (model transition shared by API + web) ---------


def test_submit_verification_creates_pending_record():
    truck = TruckFactory(verification_status=Truck.VerificationStatus.UNVERIFIED)
    verification = truck.submit_verification(
        method=TruckVerification.Method.PERMIT, evidence_note="permit #1"
    )
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.PENDING
    assert verification.status == TruckVerification.Status.PENDING
    assert truck.verifications.count() == 1


def test_submit_verification_blocked_while_pending():
    truck = TruckFactory(verification_status=Truck.VerificationStatus.PENDING)
    with pytest.raises(ValueError):
        truck.submit_verification(
            method=TruckVerification.Method.PERMIT, evidence_note="x"
        )


def test_submit_verification_blocked_while_verified():
    truck = TruckFactory(verification_status=Truck.VerificationStatus.VERIFIED)
    with pytest.raises(ValueError):
        truck.submit_verification(
            method=TruckVerification.Method.PERMIT, evidence_note="x"
        )


def test_submit_verification_allowed_after_rejection():
    truck = TruckFactory(verification_status=Truck.VerificationStatus.REJECTED)
    truck.submit_verification(
        method=TruckVerification.Method.PERMIT, evidence_note="retry"
    )
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.PENDING


@pytest.mark.parametrize(
    "vstatus,expected",
    [
        (Truck.VerificationStatus.UNVERIFIED, True),
        (Truck.VerificationStatus.REJECTED, True),
        (Truck.VerificationStatus.PENDING, False),
        (Truck.VerificationStatus.VERIFIED, False),
    ],
)
def test_can_request_verification(vstatus, expected):
    assert (
        TruckFactory(verification_status=vstatus).can_request_verification is expected
    )


@pytest.mark.parametrize(
    "status,vstatus,expected",
    [
        (Truck.Status.DRAFT, Truck.VerificationStatus.UNVERIFIED, "setup"),
        (Truck.Status.DRAFT, Truck.VerificationStatus.PENDING, "in_review"),
        (Truck.Status.DRAFT, Truck.VerificationStatus.REJECTED, "needs_attention"),
        (Truck.Status.ACTIVE, Truck.VerificationStatus.VERIFIED, "live"),
        (Truck.Status.PAUSED, Truck.VerificationStatus.VERIFIED, "paused"),
    ],
)
def test_lifecycle_state(status, vstatus, expected):
    truck = TruckFactory(status=status, verification_status=vstatus)
    assert truck.lifecycle_state == expected


# --- Approval brings the truck live -----------------------------------------


def test_approve_activates_draft_truck():
    truck = TruckFactory(
        status=Truck.Status.DRAFT,
        verification_status=Truck.VerificationStatus.PENDING,
    )
    TruckVerificationFactory(truck=truck).approve()
    truck.refresh_from_db()
    assert truck.status == Truck.Status.ACTIVE
    assert truck.verification_status == Truck.VerificationStatus.VERIFIED


def test_approve_keeps_paused_truck_paused():
    truck = TruckFactory(
        status=Truck.Status.PAUSED,
        verification_status=Truck.VerificationStatus.PENDING,
    )
    TruckVerificationFactory(truck=truck).approve()
    truck.refresh_from_db()
    assert truck.status == Truck.Status.PAUSED  # owner's pause is respected
    assert truck.verification_status == Truck.VerificationStatus.VERIFIED
