# Generated by Django 5.2.7 on 2026-06-05 07:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trucks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("location_name", models.CharField(blank=True, max_length=120)),
                ("coordinates_confirmed", models.BooleanField(default=False)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("SCHEDULED", "Scheduled"), ("CANCELED", "Canceled")],
                        default="SCHEDULED",
                        max_length=10,
                    ),
                ),
                ("last_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearances",
                        to="trucks.truck",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at"],
            },
        ),
        migrations.CreateModel(
            name="PresenceConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("CUSTOMER", "Customer")],
                        max_length=8,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("HERE_NOW", "Here now"), ("NOT_HERE", "Not here")],
                        default="HERE_NOW",
                        max_length=8,
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "appearance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to="appearances.appearance",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="appearance",
            index=models.Index(
                fields=["truck", "start_at"], name="appearances_truck_i_158880_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appearance",
            index=models.Index(
                fields=["start_at", "end_at"], name="appearances_start_a_ecf5a0_idx"
            ),
        ),
    ]
