from io import BytesIO

import pytest
from django.core.files.uploadedfile import SimpleUploadedFile
from django.urls import reverse
from PIL import Image

from apps.accounts.tests.factories import OwnerFactory, UserFactory
from apps.trucks.models import Truck, TruckVerification
from apps.trucks.tests.factories import CuisineFactory, TruckFactory

pytestmark = pytest.mark.django_db


def _tiny_png():
    """A real (tiny) PNG so the form's ImageField/Pillow validation passes."""
    buf = BytesIO()
    Image.new("RGB", (1, 1), "red").save(buf, format="PNG")
    return SimpleUploadedFile("logo.png", buf.getvalue(), content_type="image/png")


# --- Permissions gate -------------------------------------------------------


def test_create_requires_login(client):
    resp = client.get(reverse("truck-create"))
    assert resp.status_code == 302
    assert reverse("login") in resp.url


def test_create_forbidden_for_customer(client):
    client.force_login(UserFactory())  # CUSTOMER role
    assert client.get(reverse("truck-create")).status_code == 403


def test_owner_can_open_create_form(client):
    client.force_login(OwnerFactory())
    resp = client.get(reverse("truck-create"))
    assert resp.status_code == 200
    assert b"Add a truck" in resp.content


# --- Create -----------------------------------------------------------------


def test_owner_creates_truck(client):
    owner = OwnerFactory()
    cuisine = CuisineFactory()
    client.force_login(owner)
    resp = client.post(
        reverse("truck-create"),
        {
            "name": "Taco Loco",
            "primary_cuisine": cuisine.pk,
            "cuisine_tags": [],
            "description": "Best tacos in town",
        },
    )
    assert resp.status_code == 302
    truck = Truck.objects.get(name="Taco Loco")
    assert truck.owner == owner
    assert truck.slug  # autogenerated by the model
    # New trucks start as DRAFT; status is not part of the create form.
    assert truck.status == Truck.Status.DRAFT


def test_create_requires_name(client):
    client.force_login(OwnerFactory())
    resp = client.post(reverse("truck-create"), {"name": "", "cuisine_tags": []})
    assert resp.status_code == 200  # re-rendered with errors
    assert Truck.objects.count() == 0


def test_create_ignores_injected_owner(client):
    owner = OwnerFactory()
    victim = OwnerFactory()
    cuisine = CuisineFactory()
    client.force_login(owner)
    client.post(
        reverse("truck-create"),
        {
            "name": "Mine",
            "primary_cuisine": cuisine.pk,
            "cuisine_tags": [],
            "owner": victim.pk,  # owner is not a form field; must be ignored
        },
    )
    truck = Truck.objects.get(name="Mine")
    assert truck.owner == owner


def test_create_cannot_self_verify(client):
    """status/verification_status are not create-form fields: injecting them
    must not let an owner publish an unverified truck."""
    owner = OwnerFactory()
    cuisine = CuisineFactory()
    client.force_login(owner)
    client.post(
        reverse("truck-create"),
        {
            "name": "Sneaky",
            "primary_cuisine": cuisine.pk,
            "cuisine_tags": [],
            "status": Truck.Status.ACTIVE,
            "verification_status": Truck.VerificationStatus.VERIFIED,
        },
    )
    truck = Truck.objects.get(name="Sneaky")
    assert truck.status == Truck.Status.DRAFT
    assert truck.verification_status == Truck.VerificationStatus.UNVERIFIED


def test_owner_uploads_logo(client, settings, tmp_path):
    settings.MEDIA_ROOT = tmp_path  # isolate uploads from the real media dir
    owner = OwnerFactory()
    cuisine = CuisineFactory()
    client.force_login(owner)
    resp = client.post(
        reverse("truck-create"),
        {
            "name": "Pic Truck",
            "primary_cuisine": cuisine.pk,
            "cuisine_tags": [],
            "logo": _tiny_png(),
        },
    )
    assert resp.status_code == 302
    truck = Truck.objects.get(name="Pic Truck")
    assert truck.logo  # file stored


# --- Edit / ownership scoping ----------------------------------------------


def test_owner_can_edit_own_truck(client):
    owner = OwnerFactory()
    truck = TruckFactory(owner=owner, name="Old Name")
    original_slug = truck.slug
    client.force_login(owner)
    resp = client.post(
        reverse("truck-edit", args=[truck.slug]),
        {
            "name": "New Name",
            "primary_cuisine": truck.primary_cuisine.pk,
            "cuisine_tags": [],
            "description": "",
        },
    )
    assert resp.status_code == 302
    truck.refresh_from_db()
    assert truck.name == "New Name"
    # Editing details never changes live status (factory truck stays ACTIVE).
    assert truck.status == Truck.Status.ACTIVE
    # Slugs are intentionally immutable (stable URLs), matching the API where
    # slug is read-only. A rename does not change the slug.
    assert truck.slug == original_slug


def test_owner_cannot_edit_another_owners_truck(client):
    other_truck = TruckFactory()  # belongs to a different owner
    client.force_login(OwnerFactory())
    # Scoped queryset -> 404, never 403, so we don't leak that the slug exists.
    assert client.get(reverse("truck-edit", args=[other_truck.slug])).status_code == 404


def test_edit_ignores_injected_status_owner_and_verification(client):
    """Editing details cannot change status, owner, or verification, even when
    those are injected into the POST. Status changes only via the toggle."""
    owner = OwnerFactory()
    truck = TruckFactory(
        owner=owner,
        status=Truck.Status.PAUSED,
        verification_status=Truck.VerificationStatus.UNVERIFIED,
    )
    other = OwnerFactory()
    client.force_login(owner)
    client.post(
        reverse("truck-edit", args=[truck.slug]),
        {
            "name": truck.name,
            "primary_cuisine": truck.primary_cuisine.pk,
            "cuisine_tags": [],
            "status": Truck.Status.ACTIVE,  # not a form field
            "owner": other.pk,  # not a form field
            "verification_status": Truck.VerificationStatus.VERIFIED,  # not a form field
        },
    )
    truck.refresh_from_db()
    assert truck.status == Truck.Status.PAUSED
    assert truck.owner == owner
    assert truck.verification_status == Truck.VerificationStatus.UNVERIFIED


def test_cuisine_tags_persist(client):
    owner = OwnerFactory()
    truck = TruckFactory(owner=owner)
    tag_a = CuisineFactory(name="Tacos")
    tag_b = CuisineFactory(name="BBQ")
    client.force_login(owner)
    resp = client.post(
        reverse("truck-edit", args=[truck.slug]),
        {
            "name": truck.name,
            "primary_cuisine": truck.primary_cuisine.pk,
            "cuisine_tags": [tag_a.pk, tag_b.pk],
        },
    )
    assert resp.status_code == 302
    assert set(truck.cuisine_tags.values_list("pk", flat=True)) == {tag_a.pk, tag_b.pk}


def test_edit_post_another_owners_truck_404(client):
    other_truck = TruckFactory()  # different owner
    client.force_login(OwnerFactory())
    resp = client.post(
        reverse("truck-edit", args=[other_truck.slug]),
        {"name": "Hijacked", "cuisine_tags": []},
    )
    assert resp.status_code == 404
    other_truck.refresh_from_db()
    assert other_truck.name != "Hijacked"


def test_owner_uploads_hero_image(client, settings, tmp_path):
    settings.MEDIA_ROOT = tmp_path
    owner = OwnerFactory()
    cuisine = CuisineFactory()
    client.force_login(owner)
    resp = client.post(
        reverse("truck-create"),
        {
            "name": "Hero Truck",
            "primary_cuisine": cuisine.pk,
            "cuisine_tags": [],
            "hero_image": _tiny_png(),
        },
    )
    assert resp.status_code == 302
    assert Truck.objects.get(name="Hero Truck").hero_image


def test_oversized_image_rejected():
    """validate_image_size is enforced through the form. Built directly (not via
    the test client) so the faked .size survives multipart re-parsing."""
    from apps.web.forms import TruckForm

    big = _tiny_png()
    big.size = 6 * 1024 * 1024  # over the 5MB cap
    form = TruckForm(data={"name": "Too Big"}, files={"logo": big})
    assert not form.is_valid()
    assert "logo" in form.errors


# --- Status toggle (Pause / Resume, verified trucks only) ------------------


def test_pause_live_truck(client):
    owner = OwnerFactory()
    truck = TruckFactory(owner=owner)  # default ACTIVE + VERIFIED = live
    client.force_login(owner)
    client.post(reverse("truck-status-toggle", args=[truck.slug]))
    truck.refresh_from_db()
    assert truck.status == Truck.Status.PAUSED


def test_resume_paused_truck(client):
    owner = OwnerFactory()
    truck = TruckFactory(
        owner=owner,
        status=Truck.Status.PAUSED,
        verification_status=Truck.VerificationStatus.VERIFIED,
    )
    client.force_login(owner)
    client.post(reverse("truck-status-toggle", args=[truck.slug]))
    truck.refresh_from_db()
    assert truck.status == Truck.Status.ACTIVE


def test_toggle_unverified_truck_is_blocked(client):
    """An unverified truck cannot be flipped live by hand: going live is the
    result of verification approval, not this toggle."""
    owner = OwnerFactory()
    truck = TruckFactory(
        owner=owner,
        status=Truck.Status.DRAFT,
        verification_status=Truck.VerificationStatus.UNVERIFIED,
    )
    client.force_login(owner)
    resp = client.post(reverse("truck-status-toggle", args=[truck.slug]))
    assert resp.status_code == 302  # redirected with an info message
    truck.refresh_from_db()
    assert truck.status == Truck.Status.DRAFT  # unchanged


def test_toggle_requires_post(client):
    owner = OwnerFactory()
    truck = TruckFactory(owner=owner)  # live
    client.force_login(owner)
    # GET is rejected (405) so status never changes via a link or prefetch.
    resp = client.get(reverse("truck-status-toggle", args=[truck.slug]))
    assert resp.status_code == 405
    truck.refresh_from_db()
    assert truck.status == Truck.Status.ACTIVE


def test_toggle_forbidden_for_customer(client):
    truck = TruckFactory()
    client.force_login(UserFactory())  # CUSTOMER
    resp = client.post(reverse("truck-status-toggle", args=[truck.slug]))
    assert resp.status_code == 403


def test_toggle_requires_login(client):
    truck = TruckFactory()
    resp = client.post(reverse("truck-status-toggle", args=[truck.slug]))
    assert resp.status_code == 302
    assert reverse("login") in resp.url


def test_toggle_another_owners_truck_404(client):
    other_truck = TruckFactory()  # live
    client.force_login(OwnerFactory())
    resp = client.post(reverse("truck-status-toggle", args=[other_truck.slug]))
    assert resp.status_code == 404
    other_truck.refresh_from_db()
    assert other_truck.status == Truck.Status.ACTIVE  # unchanged


# --- Verification submission (chunk 5) -------------------------------------


def _setup_truck(owner):
    """A freshly created truck: draft + unverified (the 'setup' state)."""
    return TruckFactory(
        owner=owner,
        status=Truck.Status.DRAFT,
        verification_status=Truck.VerificationStatus.UNVERIFIED,
    )


def test_verify_requires_login(client):
    truck = _setup_truck(OwnerFactory())
    resp = client.get(reverse("truck-verify", args=[truck.slug]))
    assert resp.status_code == 302
    assert reverse("login") in resp.url


def test_verify_forbidden_for_customer(client):
    truck = _setup_truck(OwnerFactory())
    client.force_login(UserFactory())
    assert client.get(reverse("truck-verify", args=[truck.slug])).status_code == 403


def test_owner_can_open_verify_form(client):
    owner = OwnerFactory()
    truck = _setup_truck(owner)
    client.force_login(owner)
    resp = client.get(reverse("truck-verify", args=[truck.slug]))
    assert resp.status_code == 200
    assert b"Submit for review" in resp.content


def test_owner_submits_verification(client):
    owner = OwnerFactory()
    truck = _setup_truck(owner)
    client.force_login(owner)
    resp = client.post(
        reverse("truck-verify", args=[truck.slug]),
        {"method": TruckVerification.Method.PERMIT, "evidence_note": "permit #12345"},
    )
    assert resp.status_code == 302
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.PENDING
    assert truck.verifications.count() == 1


def test_verify_requires_evidence(client):
    owner = OwnerFactory()
    truck = _setup_truck(owner)
    client.force_login(owner)
    resp = client.post(
        reverse("truck-verify", args=[truck.slug]),
        {"method": TruckVerification.Method.PERMIT, "evidence_note": ""},
    )
    assert resp.status_code == 200  # error: needs an image or a note
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.UNVERIFIED


def test_verify_blocked_when_pending(client):
    owner = OwnerFactory()
    truck = TruckFactory(
        owner=owner, verification_status=Truck.VerificationStatus.PENDING
    )
    client.force_login(owner)
    resp = client.get(reverse("truck-verify", args=[truck.slug]))
    assert resp.status_code == 302
    assert resp.url == reverse("dashboard")


def test_verify_blocked_when_verified(client):
    owner = OwnerFactory()
    truck = TruckFactory(
        owner=owner, verification_status=Truck.VerificationStatus.VERIFIED
    )
    client.force_login(owner)
    resp = client.get(reverse("truck-verify", args=[truck.slug]))
    assert resp.status_code == 302
    assert resp.url == reverse("dashboard")


def test_verify_allowed_after_rejection(client):
    owner = OwnerFactory()
    truck = TruckFactory(
        owner=owner,
        status=Truck.Status.DRAFT,
        verification_status=Truck.VerificationStatus.REJECTED,
    )
    client.force_login(owner)
    assert client.get(reverse("truck-verify", args=[truck.slug])).status_code == 200
    resp = client.post(
        reverse("truck-verify", args=[truck.slug]),
        {"method": TruckVerification.Method.PERMIT, "evidence_note": "retry permit"},
    )
    assert resp.status_code == 302
    truck.refresh_from_db()
    assert truck.verification_status == Truck.VerificationStatus.PENDING


def test_verify_another_owners_truck_404(client):
    other_truck = _setup_truck(OwnerFactory())
    client.force_login(OwnerFactory())
    assert (
        client.get(reverse("truck-verify", args=[other_truck.slug])).status_code == 404
    )


# --- Dashboard rendering ----------------------------------------------------


def test_dashboard_shows_setup_truck(client):
    owner = OwnerFactory()
    _setup_truck(owner)
    client.force_login(owner)
    content = client.get(reverse("dashboard")).content.decode()
    assert "Not live yet" in content
    assert "Draft" not in content  # the internal label never leaks to the UI
    assert "Get verified" in content  # the CTA for a setup truck


def test_dashboard_shows_live_truck(client):
    owner = OwnerFactory()
    TruckFactory(owner=owner)  # default ACTIVE + VERIFIED = live
    client.force_login(owner)
    content = client.get(reverse("dashboard")).content.decode()
    assert "Live" in content
    assert "Pause" in content


def test_dashboard_shows_in_review_truck(client):
    owner = OwnerFactory()
    TruckFactory(
        owner=owner,
        status=Truck.Status.DRAFT,
        verification_status=Truck.VerificationStatus.PENDING,
    )
    client.force_login(owner)
    content = client.get(reverse("dashboard")).content.decode()
    assert "In review" in content


def test_dashboard_shows_needs_attention_truck(client):
    owner = OwnerFactory()
    TruckFactory(
        owner=owner,
        status=Truck.Status.DRAFT,
        verification_status=Truck.VerificationStatus.REJECTED,
    )
    client.force_login(owner)
    content = client.get(reverse("dashboard")).content.decode()
    assert "Needs attention" in content
    assert "Get verified" in content  # resubmit CTA
